# Generated by Django 4.1.7 on 2023-04-05 17:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FirstApp', '0004_users_delete_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserInfo',
        ),
    ]
